enum AppComponentCategory {
  foundation,
  actions,
  forms,
  dataDisplay,
  navigation,
  feedback,
  overlay,
  layout,
}

enum AppComponentAdapter { alias, variantFacade, wrapper, independent }

enum AppComponentStatus { planned, inProgress, implemented }

class AppComponentRegistration {
  const AppComponentRegistration({
    required this.appName,
    required this.upstreamName,
    required this.category,
    required this.adapter,
    required this.status,
  });

  final String appName;
  final String upstreamName;
  final AppComponentCategory category;
  final AppComponentAdapter adapter;
  final AppComponentStatus status;
}

abstract final class AppComponentRegistry {
  static const components = <AppComponentRegistration>[
    AppComponentRegistration(
      appName: 'AppVisualStyle',
      upstreamName: 'InheritedWidget',
      category: AppComponentCategory.foundation,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppControlMetrics',
      upstreamName: 'Control sizing defaults',
      category: AppComponentCategory.foundation,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppMotion',
      upstreamName: 'Animation primitives',
      category: AppComponentCategory.foundation,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppShadcnScope',
      upstreamName: 'ShadcnLayer',
      category: AppComponentCategory.foundation,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppButton',
      upstreamName: 'Button variants',
      category: AppComponentCategory.actions,
      adapter: AppComponentAdapter.variantFacade,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppToggle',
      upstreamName: 'Toggle',
      category: AppComponentCategory.actions,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppField',
      upstreamName: 'Form field layout',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppForm',
      upstreamName: 'Form',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppAsyncOptionSource',
      upstreamName: 'Future option loading',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppAsyncPagedOptionSource',
      upstreamName: 'Future paged option loading',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTextFormField',
      upstreamName: 'TextField',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSelect',
      upstreamName: 'Select',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSelectFormField',
      upstreamName: 'Select',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppAutoCompleteFormField',
      upstreamName: 'SelectPopup.builder',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppCheckbox',
      upstreamName: 'Checkbox',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppChipInput',
      upstreamName: 'ChipInput',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSwitch',
      upstreamName: 'Switch',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppRadioGroup',
      upstreamName: 'RadioGroup',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSlider',
      upstreamName: 'Slider',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppStarRating',
      upstreamName: 'StarRating',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTextArea',
      upstreamName: 'TextArea',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppInputOtp',
      upstreamName: 'InputOTP',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppPhoneInput',
      upstreamName: 'PhoneInput',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppDatePicker',
      upstreamName: 'DatePicker / DateRangePicker',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.variantFacade,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTimePicker',
      upstreamName: 'ObjectFormField / TimeOfDay',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppDateTimePicker',
      upstreamName: 'ObjectFormField / DatePickerDialog / TimeOfDay',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppLegacyTimePicker',
      upstreamName: 'TimePicker',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTimeStepperPicker',
      upstreamName: 'TimeOfDay',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppCalendar',
      upstreamName: 'Calendar',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppAvatar',
      upstreamName: 'Avatar',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppAvatarGroup',
      upstreamName: 'AvatarGroup',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppBadge',
      upstreamName: 'Badge variants',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.variantFacade,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppCodeSnippet',
      upstreamName: 'CodeSnippet',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppProgress',
      upstreamName: 'Progress',
      category: AppComponentCategory.feedback,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppCircularProgressIndicator',
      upstreamName: 'CircularProgressIndicator',
      category: AppComponentCategory.feedback,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppLinearProgressIndicator',
      upstreamName: 'LinearProgressIndicator',
      category: AppComponentCategory.feedback,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppNumberTicker',
      upstreamName: 'NumberTicker',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppAnimatedValueBuilder',
      upstreamName: 'AnimatedValueBuilder',
      category: AppComponentCategory.foundation,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppRepeatedAnimationBuilder',
      upstreamName: 'RepeatedAnimationBuilder',
      category: AppComponentCategory.foundation,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSkeleton',
      upstreamName: 'SkeletonExtension',
      category: AppComponentCategory.feedback,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppDotIndicator',
      upstreamName: 'DotIndicator',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppRefreshTrigger',
      upstreamName: 'RefreshTrigger',
      category: AppComponentCategory.feedback,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSwiper',
      upstreamName: 'Swiper',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppBackdropTransform',
      upstreamName: 'BackdropTransform',
      category: AppComponentCategory.overlay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppOverflowMarquee',
      upstreamName: 'OverflowMarquee',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppScrollbar',
      upstreamName: 'Scrollbar',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSelectableText',
      upstreamName: 'SelectableText',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppBreadcrumb',
      upstreamName: 'Breadcrumb',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppPagination',
      upstreamName: 'Pagination',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTabs',
      upstreamName: 'Tabs',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTabList',
      upstreamName: 'TabList',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSwitcher',
      upstreamName: 'Switcher',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSteps',
      upstreamName: 'Steps',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.variantFacade,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTimeline',
      upstreamName: 'Timeline',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.variantFacade,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppCarousel',
      upstreamName: 'Carousel',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppResizable',
      upstreamName: 'ResizablePanel',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppStepper',
      upstreamName: 'Stepper',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTree',
      upstreamName: 'Tree',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTreeItem',
      upstreamName: 'TreeItem',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTable',
      upstreamName: 'Table',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppScaffold',
      upstreamName: 'Scaffold',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppAlertDialog',
      upstreamName: 'AlertDialog',
      category: AppComponentCategory.feedback,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppFormDialog',
      upstreamName: 'AlertDialog',
      category: AppComponentCategory.overlay,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppDialog',
      upstreamName: 'DialogConfiguration',
      category: AppComponentCategory.overlay,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppDrawer',
      upstreamName: 'DrawerConfiguration',
      category: AppComponentCategory.overlay,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSheet',
      upstreamName: 'SheetConfiguration',
      category: AppComponentCategory.overlay,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppPopover',
      upstreamName: 'PopoverConfiguration',
      category: AppComponentCategory.overlay,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppHoverCard',
      upstreamName: 'HoverCard',
      category: AppComponentCategory.overlay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTooltip',
      upstreamName: 'Tooltip',
      category: AppComponentCategory.overlay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppToast',
      upstreamName: 'showToast',
      category: AppComponentCategory.feedback,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppInput',
      upstreamName: 'TextField input primitive',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppFormattedInput',
      upstreamName: 'FormattedInput',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppColorInput',
      upstreamName: 'ColorInput',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppColorPicker',
      upstreamName: 'ColorPicker',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppMultipleChoice',
      upstreamName: 'MultipleChoice',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppItemPicker',
      upstreamName: 'ItemPicker',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppImageInput',
      upstreamName: 'Image input (upstream placeholder)',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSortableInput',
      upstreamName: 'RawSortableList',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppObjectInput',
      upstreamName: 'FormattedObjectInput',
      category: AppComponentCategory.forms,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppMenubar',
      upstreamName: 'Menubar',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppNavigationMenu',
      upstreamName: 'NavigationMenu',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppCommand',
      upstreamName: 'Command',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppContextMenu',
      upstreamName: 'ContextMenu',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppDropdownMenu',
      upstreamName: 'DropdownMenu',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppKeyboardDisplay',
      upstreamName: 'KeyboardDisplay',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppAsyncView',
      upstreamName: 'FutureOrBuilder',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppChat',
      upstreamName: 'ChatGroup',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppPinnedSheet',
      upstreamName: 'PinnedSheet',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppNavigationBar',
      upstreamName: 'NavigationBar',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppWindow',
      upstreamName: 'Window',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppTracker',
      upstreamName: 'Tracker',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppChip',
      upstreamName: 'Chip',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppAccordion',
      upstreamName: 'Accordion',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppCollapsible',
      upstreamName: 'Collapsible',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppAlert',
      upstreamName: 'Alert',
      category: AppComponentCategory.feedback,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppCard',
      upstreamName: 'Card',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppDivider',
      upstreamName: 'Divider',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppOutlinedContainer',
      upstreamName: 'OutlinedContainer',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.alias,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppText',
      upstreamName: 'Typography / Text',
      category: AppComponentCategory.dataDisplay,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppDropdownButton',
      upstreamName: 'showDropdown / DropdownMenu',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.wrapper,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppShell',
      upstreamName: 'Scaffold / navigation composition',
      category: AppComponentCategory.layout,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
    AppComponentRegistration(
      appName: 'AppSidebar',
      upstreamName: 'Button / HoverCard / Drawer composition',
      category: AppComponentCategory.navigation,
      adapter: AppComponentAdapter.independent,
      status: AppComponentStatus.implemented,
    ),
  ];
}
